-- MySQL Script generated by MySQL Workbench
-- Tue Aug  4 23:09:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school` ;

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8mb4 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`college`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`college` ;

CREATE TABLE IF NOT EXISTS `school`.`college` (
  `college_id` INT NOT NULL AUTO_INCREMENT,
  `college_name` VARCHAR(64) NULL DEFAULT NULL,
  `student_count` INT NULL DEFAULT 0,
  PRIMARY KEY (`college_id`));


-- -----------------------------------------------------
-- Table `school`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`major` ;

CREATE TABLE IF NOT EXISTS `school`.`major` (
  `major_id` INT NOT NULL AUTO_INCREMENT,
  `college_id` INT NOT NULL,
  `major_name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`major_id`),
  INDEX `fk_majar_college_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `fk_majar_college`
    FOREIGN KEY (`college_id`)
    REFERENCES `school`.`college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `school`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`teacher` ;

CREATE TABLE IF NOT EXISTS `school`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `gender` CHAR(2) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `phone` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`teacher_id`));


-- -----------------------------------------------------
-- Table `school`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`class` ;

CREATE TABLE IF NOT EXISTS `school`.`class` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `major_id` INT NOT NULL,
  `student_count` INT NULL DEFAULT 0,
  `head_teacher_id` INT NOT NULL,
  PRIMARY KEY (`class_id`),
  INDEX `fk_class_major_idx` (`major_id` ASC) VISIBLE,
  INDEX `fk_class_teacher_idx` (`head_teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_major`
    FOREIGN KEY (`major_id`)
    REFERENCES `school`.`major` (`major_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_teacher`
    FOREIGN KEY (`head_teacher_id`)
    REFERENCES `school`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `school`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`address` ;

CREATE TABLE IF NOT EXISTS `school`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `province` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`student` ;

CREATE TABLE IF NOT EXISTS `school`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `gender` CHAR(2) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `class_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `phone` VARCHAR(16) NULL DEFAULT NULL,
  `total_credits` DECIMAL(5,1) NULL DEFAULT 0,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_class_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_student_address_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `school`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `school`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `school`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`course` ;

CREATE TABLE IF NOT EXISTS `school`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(64) NULL DEFAULT NULL,
  `credit` DECIMAL(4,1) NULL DEFAULT NULL,
  `class_hours` INT NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`));


-- -----------------------------------------------------
-- Table `school`.`building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`building` ;

CREATE TABLE IF NOT EXISTS `school`.`building` (
  `building_id` INT NOT NULL AUTO_INCREMENT,
  `building_name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`building_id`));


-- -----------------------------------------------------
-- Table `school`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`classroom` ;

CREATE TABLE IF NOT EXISTS `school`.`classroom` (
  `classroom_id` INT NOT NULL AUTO_INCREMENT,
  `building_id` INT NOT NULL,
  `college_id` INT NOT NULL,
  PRIMARY KEY (`classroom_id`),
  INDEX `fk_classroom_building_idx` (`building_id` ASC) VISIBLE,
  INDEX `fk_classroom_college_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `fk_classroom_building`
    FOREIGN KEY (`building_id`)
    REFERENCES `school`.`building` (`building_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_college`
    FOREIGN KEY (`college_id`)
    REFERENCES `school`.`college` (`college_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `school`.`training_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`training_plan` ;

CREATE TABLE IF NOT EXISTS `school`.`training_plan` (
  `course_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `semester` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`course_id`, `class_id`, `semester`),
  INDEX `fk_train_class_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_train_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `school`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_train_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `school`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `school`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`score` ;

CREATE TABLE IF NOT EXISTS `school`.`score` (
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `score` DECIMAL(5,2) NULL DEFAULT NULL,
  `earned_credit` DECIMAL(4,1) NULL DEFAULT 0,
  PRIMARY KEY (`course_id`, `student_id`),
  INDEX `fk_score_student_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_score_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `school`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `school`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `school`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`schedule` ;

CREATE TABLE IF NOT EXISTS `school`.`schedule` (
  `course_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `semester` VARCHAR(16) NOT NULL,
  `weekday` VARCHAR(8) NOT NULL,
  `period` VARCHAR(8) NOT NULL,
  `teacher_id` INT NOT NULL,
  `classroom_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `class_id`, `semester`, `weekday`, `period`),
  UNIQUE INDEX `uk_teacher_time` (`teacher_id` ASC, `semester` ASC, `weekday` ASC, `period` ASC) VISIBLE,
  UNIQUE INDEX `uk_classroom_time` (`classroom_id` ASC, `semester` ASC, `weekday` ASC, `period` ASC) VISIBLE,
  CONSTRAINT `fk_sche_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sche_classroom`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `school`.`classroom` (`classroom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
